services:
  php:
    restart: unless-stopped

    image: ${PHP_IMAGE}
    # build:
    #   context: .
    #   dockerfile: ${DOCKERFILE}
    volumes:
      # - ../../../:/var/www/html
      - ./:/var/www/html
    ports:
      - ${APACHE_PORT}:80